
name: prod

on:
  push:
    branches:
      - updates

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    run:
     - echo "deploying application.."
      

